// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ePunla.Common.Database;

namespace ePunla.Common.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210418135038_addedAdditionalModel")]
    partial class addedAdditionalModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ePunla.Common.Database.Models.Barangay", b =>
                {
                    b.Property<int>("BarangayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BarangayId");

                    b.ToTable("Barangays");
                });

            modelBuilder.Entity("ePunla.Common.Database.Models.BarangayArea", b =>
                {
                    b.Property<int>("BarangayAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BarangayId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BarangayAreaId");

                    b.HasIndex("BarangayId");

                    b.ToTable("BarangayAreas");
                });

            modelBuilder.Entity("ePunla.Common.Database.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ePunla.Common.Database.Models.Claim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DamagedArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FarmCropId")
                        .HasColumnType("int");

                    b.Property<int?>("FarmId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FilingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhotoId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ClaimId");

                    b.HasIndex("FarmCropId");

                    b.HasIndex("FarmId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("ePunla.Common.Database.Models.ClaimCause", b =>
                {
                    b.Property<int>("ClaimCauseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClaimId")
                        .HasColumnType("int");

                    b.Property<string>("DamageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DamagedAreaSize")
                        .HasColumnType("int");

                    b.HasKey("ClaimCauseId");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimCauses");
                });

            modelBuilder.Entity("ePunla.Common.Database.Models.Crop", b =>
                {
                    b.Property<int>("CropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CropId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("ePunla.Common.Database.Models.Farm", b =>
                {
                    b.Property<int>("FarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AreaSize")
                        .HasColumnType("int");

                    b.Property<int?>("BarangayAreaId")
                        .HasColumnType("int");

                    b.Property<int?>("BarangayId")
                        .HasColumnType("int");

                    b.Property<int?>("FarmerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FarmId");

                    b.HasIndex("BarangayAreaId");

                    b.HasIndex("BarangayId");

                    b.HasIndex("FarmerId");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("ePunla.Common.Database.Models.FarmCrop", b =>
                {
                    b.Property<int>("FarmCropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AreaSize")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CropId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EstimatedHarvestDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FarmId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HarvestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlantedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FarmCropId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CropId");

                    b.HasIndex("FarmId");

                    b.ToTable("FarmCrops");
                });

            modelBuilder.Entity("ePunla.Common.Database.Models.Farmer", b =>
                {
                    b.Property<int>("FarmerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AvatarId")
                        .HasColumnType("int");

                    b.Property<int?>("BarangayAreaId")
                        .HasColumnType("int");

                    b.Property<int?>("BarangayId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("FarmerId");

                    b.HasIndex("BarangayAreaId");

                    b.HasIndex("BarangayId");

                    b.ToTable("Farmers");
                });

            modelBuilder.Entity("ePunla.Common.Database.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ePunla.Common.Database.Models.BarangayArea", b =>
                {
                    b.HasOne("ePunla.Common.Database.Models.Barangay", "Barangay")
                        .WithMany()
                        .HasForeignKey("BarangayId");
                });

            modelBuilder.Entity("ePunla.Common.Database.Models.Claim", b =>
                {
                    b.HasOne("ePunla.Common.Database.Models.FarmCrop", "FarmCrop")
                        .WithMany()
                        .HasForeignKey("FarmCropId");

                    b.HasOne("ePunla.Common.Database.Models.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId");
                });

            modelBuilder.Entity("ePunla.Common.Database.Models.ClaimCause", b =>
                {
                    b.HasOne("ePunla.Common.Database.Models.Claim", "Claim")
                        .WithMany()
                        .HasForeignKey("ClaimId");
                });

            modelBuilder.Entity("ePunla.Common.Database.Models.Crop", b =>
                {
                    b.HasOne("ePunla.Common.Database.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("ePunla.Common.Database.Models.Farm", b =>
                {
                    b.HasOne("ePunla.Common.Database.Models.BarangayArea", "BarangayArea")
                        .WithMany()
                        .HasForeignKey("BarangayAreaId");

                    b.HasOne("ePunla.Common.Database.Models.Barangay", "Barangay")
                        .WithMany()
                        .HasForeignKey("BarangayId");

                    b.HasOne("ePunla.Common.Database.Models.Farmer", "Farmer")
                        .WithMany()
                        .HasForeignKey("FarmerId");
                });

            modelBuilder.Entity("ePunla.Common.Database.Models.FarmCrop", b =>
                {
                    b.HasOne("ePunla.Common.Database.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("ePunla.Common.Database.Models.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId");

                    b.HasOne("ePunla.Common.Database.Models.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId");
                });

            modelBuilder.Entity("ePunla.Common.Database.Models.Farmer", b =>
                {
                    b.HasOne("ePunla.Common.Database.Models.BarangayArea", "BarangayArea")
                        .WithMany()
                        .HasForeignKey("BarangayAreaId");

                    b.HasOne("ePunla.Common.Database.Models.Barangay", "Barangay")
                        .WithMany()
                        .HasForeignKey("BarangayId");
                });
#pragma warning restore 612, 618
        }
    }
}
