// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ePunla.Common.Database;

namespace ePunla.Common.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210418131744_modifiedBarangayModel")]
    partial class modifiedBarangayModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ePunla.Common.Database.Models.Barangay", b =>
                {
                    b.Property<int>("BarangayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BarangayId");

                    b.ToTable("Barangays");
                });

            modelBuilder.Entity("ePunla.Common.Database.Models.BarangayArea", b =>
                {
                    b.Property<int>("BarangayAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BarangayId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BarangayAreaId");

                    b.HasIndex("BarangayId");

                    b.ToTable("BarangayAreas");
                });

            modelBuilder.Entity("ePunla.Common.Database.Models.Farmer", b =>
                {
                    b.Property<int>("FarmerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AvatarId")
                        .HasColumnType("int");

                    b.Property<int?>("BarangayAreaId")
                        .HasColumnType("int");

                    b.Property<int?>("BarangayId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ValidationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("FarmerId");

                    b.HasIndex("BarangayAreaId");

                    b.HasIndex("BarangayId");

                    b.ToTable("Farmers");
                });

            modelBuilder.Entity("ePunla.Common.Database.Models.BarangayArea", b =>
                {
                    b.HasOne("ePunla.Common.Database.Models.Barangay", "Barangay")
                        .WithMany()
                        .HasForeignKey("BarangayId");
                });

            modelBuilder.Entity("ePunla.Common.Database.Models.Farmer", b =>
                {
                    b.HasOne("ePunla.Common.Database.Models.BarangayArea", "BarangayArea")
                        .WithMany()
                        .HasForeignKey("BarangayAreaId");

                    b.HasOne("ePunla.Common.Database.Models.Barangay", "Barangay")
                        .WithMany()
                        .HasForeignKey("BarangayId");
                });
#pragma warning restore 612, 618
        }
    }
}
